# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-aath0-github-io'

google-ID: 'UA-118662545-1'

menu:
- {name: 'About', path: 'menu', url: 'about.html'}
- {name: 'Posts', path: 'menu', url: 'posts.html'}
- {name: 'Resources', path: 'menu', url: 'resources.html'}
- {name: 'Contact', path: 'menu', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/aath0'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/ethanwicker/'}
- {icon: 'envelope', link: 'mailto:athina.tz@gmail.com'}


# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
