# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-aath0-github-io'

google-ID: 'UA-103680525-1'

menu:
- {name: 'CV', path: 'https://aath0.github.io', url: 'about.html'}
- {name: 'Coma & Consciousness', path: 'https://aath0.github.io/', url: 'coma.html'}
- {name: 'Methods', path: 'https://aath0.github.io', url: 'methods.html'}
- {name: 'Material', path: 'https://aath0.github.io', url: 'open.html'}
- {name: 'Publications', path: 'https://scholar.google.ch/citations?user=XdOdIKYAAAAJ&hl=en', url: ''}
- {name: 'Contact', path: 'https://aath0.github.io', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/aath0'}
- {icon: 'twitter', link: 'https://www.twitter.com/aath0'}
- {icon: 'envelope', link: 'mailto:athina.tz@gmail.com'}


# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
